### ISSUE TITLE
error:__init__() missing 1 required positional argument: 'hparams'

### ISSUE THREAD

**Issue by volcanoxs** [teddykoker/unsupervised-deep-homography#12]
Thanks for your great jobs!
when I test my own images,there is an error.I find it will occured because the checkpoint doesn't have the hyparameter.So how can I solve this problem?

**Comment by teddykoker** [comment]
Hi! Are you using the version of Pytorch Lightning specified in requirements.txt?

**Comment by volcanoxs** [comment]
Thanks.
The problem has been solved

**Comment by volcanoxs** [comment]
If the image has a moving foreground or contains two homography ,the model will perform badly.Am I right?

**Comment by teddykoker** [comment]
This model doesn't perform that well overall. That being said a change in foreground could certainly cause an incorrect prediction as well. If you are looking for the best performance it might be worth looking into RANSAC using ResNet features (or potentially newer approaches; I have not been following the literature for image alignment recently)
