### ISSUE TITLE
the pytorch_lightning is update  and your code went wrong

### ISSUE THREAD

**Issue by ywz978020607** [teddykoker/unsupervised-deep-homography#15]
why you use the pytorch_lightning ?  now the code in train.py shows that the hparams can't be set attributes.

**Comment by teddykoker** [comment]
I'm having trouble understanding your issue - do you think you could rephrase or clarify?

**Comment by ywz978020607** [comment]
Finally,.. I found that in the newest version of pytorch_lightning, the hparams variable can’t be set attribute and caused an error.  The way to the problem is : change the hparams to other name like “myargs”.
Yesterday I found that the code of last year which didn’t  change anything couldn’t run in the new environment and made me crazy haha. Anyway, happy new year.
