### ISSUE TITLE
Something About The Spatial Tranformation

### ISSUE THREAD

**Issue by Acmenwangtuo** [teddykoker/unsupervised-deep-homography#20]
I want to know the code
`    patch_b_hat = kornia.warp_perspective(img_a, h_inv, (128, 128))
`
Equivalent to
the whole Spatial Transformation ?

**Comment by teddykoker** [comment]
Yes, `kornia.warp_perspective`, (now [`kornia.geometry.transform.warp_perspective`](https://kornia.readthedocs.io/en/v0.6.4/geometry.transform.html#kornia.geometry.transform.warp_perspective)) applies the spatial transformation.
