### ISSUE TITLE
Something About Tensor Direct Linear Transform

### ISSUE THREAD

**Issue by Lu-Feng** [teddykoker/unsupervised-deep-homography#23]
Hello,thanks for your codes.
I want to know the code
  h = kornia.get_perspective_transform(corners, corners_hat)
Equivalent to the Tensor Direct Linear Transform in the paper?

**Comment by teddykoker** [comment]
Yes! [`kornia.get_perspective_transform`](https://kornia.readthedocs.io/en/latest/geometry.transform.html#kornia.geometry.transform.get_perspective_transform) performs a direct linear transform (DLT) like the paper.
