### ISSUE TITLE
L1 loss

### ISSUE THREAD

**Issue by dkoguciuk** [teddykoker/unsupervised-deep-homography#5]
Hi @teddykoker ,

I think there could be a bug in your photometric_loss function. As far as I understand, the paper says we use estimated homography to warp the input image **crop the hypothetical patch_2** and compare it with the actual **patch_2**. But you're comparing **patch_2** with the warped input image. On in other words, instead of:

`patch_b_hat = kornia.warp_perspective(img_a, h_inv, (128, 128))`

it should be (it's pseudocode, not the real working fix):

`
image_warped = kornia.warp_perspective(img_a, h_inv, tuple(img_a.shape[-2:][::-1])
patch_b_hat = image_warped[:, corners[0, 1]:corners[3, 1], corners[0, 0]:corners[1, 0]]
`

I am refering to [this](https://github.com/teddykoker/unsupervised-deep-homography/blob/master/model.py#L17) line. What do you think?

**Comment by teddykoker** [comment]
Hey Daniel, thanks for reading through the code!

You are correct in that the image needs to be cropped after the homography is applied. This is done indirectly in the few lines above:

```python
corners_hat = corners + delta
# in order to apply transform and center crop,
# subtract points by top-left corner (corners[N, 0])
corners = corners - corners[:, 0].view(-1, 1, 2)
h = kornia.get_perspective_transform(corners, corners_hat)
```

By moving the corner of the crop to (0,0), we move the whole crop within [0,128] which will then be cropped out with `kornia.warp_perspective(img_a, h_inv, (128, 128))`. I initially tried something like your approach, but I found it hard to vectorize the center crop operation (as each image needs to be cropped at a different location).

**Comment by dkoguciuk** [comment]
Brilliant!
